Repository adopted-ember-addons/ember-launch-darkly, pull requests merged in 2025-04, with the labels that each got.

#573 Add correct repository
  ember-launch-darkly/package.json
Labels: bug

#591 Make tracked-built-ins a peerDep
  ember-launch-darkly/package.json
  pnpm-lock.yaml
Labels: breaking

#592 Make @ember/test-helpers a peerDep
  ember-launch-darkly/package.json
  pnpm-lock.yaml
  test-app/package.json
Labels: breaking

#607 some times config maybe unresolved but we should still continue
  ember-launch-darkly/src/test-support/setup-launch-darkly.js
Labels: bug

#608 Bump pnpm to v10.9.0
  README.md
  package.json
Labels: internal

#616 Add typescript/glint support
  config/ember-cli-update.json
  ember-launch-darkly/babel.config.json
  ember-launch-darkly/eslint.config.mjs
  ember-launch-darkly/package.json
  ember-launch-darkly/rollup.config.mjs
  ember-launch-darkly/src/-sdk/context.ts
  ember-launch-darkly/src/-sdk/identify.js
  ember-launch-darkly/src/-sdk/identify.ts
  ember-launch-darkly/src/-sdk/index.js
  ember-launch-darkly/src/-sdk/index.ts
  ember-launch-darkly/src/-sdk/initialize.js
  ember-launch-darkly/src/-sdk/initialize.ts
  ember-launch-darkly/src/-sdk/variation.js
  ember-launch-darkly/src/-sdk/variation.ts
  ember-launch-darkly/src/helpers/variation.ts
  ember-launch-darkly/src/index.js
  ember-launch-darkly/src/index.ts
  ember-launch-darkly/src/template-registry.ts
  ember-launch-darkly/src/test-support/setup-launch-darkly.js
  ember-launch-darkly/src/test-support/setup-launch-darkly.ts
  ember-launch-darkly/tsconfig.json
  ember-launch-darkly/unpublished-development-types/index.d.ts
  package.json
  pnpm-lock.yaml
  test-app/.ember-cli
  test-app/app/app.ts
  test-app/app/config/environment.d.ts
  test-app/app/deprecation-workflow.ts
  test-app/app/router.ts
  test-app/config/ember-cli-update.json
  test-app/ember-cli-build.js
  test-app/eslint.config.mjs
  test-app/package.json
  test-app/tests/helpers/index.ts
  test-app/tests/test-helper.ts
  test-app/types/global.d.ts
Labels: enhancement

#609 Add back reexport for test-support
  README.md
  ember-launch-darkly/src/test-support.ts
  test-app/tests/integration/helpers/variation-test.js
Labels: enhancement

#619 Make variation generic
  ember-launch-darkly/src/-sdk/context.ts
  ember-launch-darkly/src/-sdk/variation.ts
Labels: bug

#622 Try again to fix generic types
  ember-launch-darkly/src/-sdk/context.ts
  ember-launch-darkly/src/-sdk/variation.ts
Labels: bug

#624 Tweak generics again
  ember-launch-darkly/src/-sdk/context.ts
  ember-launch-darkly/src/-sdk/variation.ts
Labels: bug

#626 Make Context more generic
  ember-launch-darkly/src/-sdk/context.ts
  ember-launch-darkly/src/-sdk/variation.ts
Labels: bug
